services:
  api:
    container_name: dev_api
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=cahcards
      - DB_CONNECTION=mongodb://cahadmin:31Hadm1nPass!@db:27017
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
    
    # socket:
    #   container_name: socket_api
    #   ports:
    #     - 5001:5001
    #   environment:
    #     - NODE_ENV=development
    #   command: bash -c "npm install && npm run dev"
  
  db:
    volumes:
      - "dev_db:/var/lib/mongodb/data"
      - "./db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=cahadmin
      - MONGO_INITDB_DATABASE=cahcards
      - MONGO_INITDB_ROOT_PASSWORD=31Hadm1nPass!
volumes:
  dev_db: